spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: hks13579
      driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  # ??? ??? Job? ????? ??, ?? ???? ???? ????? ??
  # ex. --job.name=stepNextJob
  batch:
    job:
      name: ${job.name:NONE}